// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2TnzRq6DzD8JFQhzdK8q0glBuwCJqN9k',
    appId: '1:157455092009:web:981fda56711e5e4fd40f38',
    messagingSenderId: '157455092009',
    projectId: 'kacomania-conecta',
    authDomain: 'kacomania-conecta.firebaseapp.com',
    storageBucket: 'kacomania-conecta.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxzBe4AwO02XnGZnf_5cldSAtFLFKt3V4',
    appId: '1:157455092009:android:228311f10ac7428ad40f38',
    messagingSenderId: '157455092009',
    projectId: 'kacomania-conecta',
    storageBucket: 'kacomania-conecta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlf0zDr8dWYJdZxpPWY38G5xA82omzqV4',
    appId: '1:157455092009:ios:346bf1c9c541d99dd40f38',
    messagingSenderId: '157455092009',
    projectId: 'kacomania-conecta',
    storageBucket: 'kacomania-conecta.firebasestorage.app',
    iosBundleId: 'com.example.cidadaoConecta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2TnzRq6DzD8JFQhzdK8q0glBuwCJqN9k',
    appId: '1:157455092009:web:d6fb36f47c93803cd40f38',
    messagingSenderId: '157455092009',
    projectId: 'kacomania-conecta',
    authDomain: 'kacomania-conecta.firebaseapp.com',
    storageBucket: 'kacomania-conecta.firebasestorage.app',
  );
}
